# Generated by Django 6.0.3 on 2026-04-10 08:09

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_notification_room_notification_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.chat_file_upload_path),
        ),
    ]
